export const FETCH_COUNTRY_DATA = "FETCH_COUNTRY_DATA";
export const IS_LOADING_TRUE = "IS_LOADING_TRUE";
export const IS_LOADING_FALSE = "IS_LOADING_FALSE";
export const FETCH_COUNTRY_EXPORT_DATA = "FETCH_COUNTRY_EXPORT_DATA";
export const FETCH_COUNTRY_IMPORT_DATA = "FETCH_COUNTRY_IMPORT_DATA";